package com.supertone.supertonic.ui.theme

import androidx.compose.ui.graphics.Color

// Purple Theme (Default)
val PurplePrimary = Color(0xFF7C4DFF)
val PurpleOnPrimary = Color(0xFFFFFFFF)
val PurplePrimaryContainer = Color(0xFFE8DDFF)
val PurpleOnPrimaryContainer = Color(0xFF21005D)
val PurpleSecondary = Color(0xFF625B71)
val PurpleOnSecondary = Color(0xFFFFFFFF)
val PurpleSecondaryContainer = Color(0xFFE8DEF8)
val PurpleOnSecondaryContainer = Color(0xFF1D192B)
val PurpleTertiary = Color(0xFF7D5260)
val PurpleOnTertiary = Color(0xFFFFFFFF)
val PurpleTertiaryContainer = Color(0xFFFFD8E4)
val PurpleOnTertiaryContainer = Color(0xFF31111D)
val PurpleBackground = Color(0xFFFFFBFE)
val PurpleOnBackground = Color(0xFF1C1B1F)
val PurpleSurface = Color(0xFFFFFBFE)
val PurpleOnSurface = Color(0xFF1C1B1F)
val PurpleSurfaceVariant = Color(0xFFE7E0EC)
val PurpleOnSurfaceVariant = Color(0xFF49454E)
val PurpleOutline = Color(0xFF79747E)

// Purple Dark
val PurplePrimaryDark = Color(0xFFCFBCFF)
val PurpleOnPrimaryDark = Color(0xFF381E72)
val PurplePrimaryContainerDark = Color(0xFF4F378B)
val PurpleOnPrimaryContainerDark = Color(0xFFE8DDFF)
val PurpleSecondaryDark = Color(0xFFCCC2DC)
val PurpleOnSecondaryDark = Color(0xFF332D41)
val PurpleSecondaryContainerDark = Color(0xFF4A4458)
val PurpleOnSecondaryContainerDark = Color(0xFFE8DEF8)
val PurpleTertiaryDark = Color(0xFFEFB8C8)
val PurpleOnTertiaryDark = Color(0xFF492532)
val PurpleTertiaryContainerDark = Color(0xFF633B48)
val PurpleOnTertiaryContainerDark = Color(0xFFFFD8E4)
val PurpleBackgroundDark = Color(0xFF1C1B1F)
val PurpleOnBackgroundDark = Color(0xFFE6E1E5)
val PurpleSurfaceDark = Color(0xFF1C1B1F)
val PurpleOnSurfaceDark = Color(0xFFE6E1E5)
val PurpleSurfaceVariantDark = Color(0xFF49454E)
val PurpleOnSurfaceVariantDark = Color(0xFFCAC4D0)
val PurpleOutlineDark = Color(0xFF938F99)

// Teal Theme
val TealPrimary = Color(0xFF00897B)
val TealOnPrimary = Color(0xFFFFFFFF)
val TealPrimaryContainer = Color(0xFFA7F3E5)
val TealOnPrimaryContainer = Color(0xFF002019)
val TealSecondary = Color(0xFF4A635D)
val TealOnSecondary = Color(0xFFFFFFFF)
val TealSecondaryContainer = Color(0xFFCCE8E0)
val TealOnSecondaryContainer = Color(0xFF05201B)
val TealBackground = Color(0xFFFAFDFA)
val TealOnBackground = Color(0xFF191C1B)
val TealSurface = Color(0xFFFAFDFA)
val TealOnSurface = Color(0xFF191C1B)
val TealSurfaceVariant = Color(0xFFDAE5E0)
val TealOnSurfaceVariant = Color(0xFF3F4946)
val TealOutline = Color(0xFF6F7976)

// Teal Dark
val TealPrimaryDark = Color(0xFF4FDBC8)
val TealOnPrimaryDark = Color(0xFF00382E)
val TealPrimaryContainerDark = Color(0xFF005045)
val TealOnPrimaryContainerDark = Color(0xFFA7F3E5)
val TealSecondaryDark = Color(0xFFB0CCC4)
val TealOnSecondaryDark = Color(0xFF1C352F)
val TealSecondaryContainerDark = Color(0xFF324B45)
val TealOnSecondaryContainerDark = Color(0xFFCCE8E0)
val TealBackgroundDark = Color(0xFF191C1B)
val TealOnBackgroundDark = Color(0xFFE1E3E0)
val TealSurfaceDark = Color(0xFF191C1B)
val TealOnSurfaceDark = Color(0xFFE1E3E0)
val TealSurfaceVariantDark = Color(0xFF3F4946)
val TealOnSurfaceVariantDark = Color(0xFFBEC9C4)
val TealOutlineDark = Color(0xFF89938F)

// Orange Theme
val OrangePrimary = Color(0xFFFF6D00)
val OrangeOnPrimary = Color(0xFFFFFFFF)
val OrangePrimaryContainer = Color(0xFFFFDBCC)
val OrangeOnPrimaryContainer = Color(0xFF2D1600)
val OrangeSecondary = Color(0xFF765848)
val OrangeOnSecondary = Color(0xFFFFFFFF)
val OrangeSecondaryContainer = Color(0xFFFFDBCC)
val OrangeOnSecondaryContainer = Color(0xFF2C160A)
val OrangeBackground = Color(0xFFFFFBFF)
val OrangeOnBackground = Color(0xFF201A17)
val OrangeSurface = Color(0xFFFFFBFF)
val OrangeOnSurface = Color(0xFF201A17)
val OrangeSurfaceVariant = Color(0xFFF4DED4)
val OrangeOnSurfaceVariant = Color(0xFF52443C)
val OrangeOutline = Color(0xFF85736A)

// Orange Dark
val OrangePrimaryDark = Color(0xFFFFB68F)
val OrangeOnPrimaryDark = Color(0xFF4E2600)
val OrangePrimaryContainerDark = Color(0xFF6F3900)
val OrangeOnPrimaryContainerDark = Color(0xFFFFDBCC)
val OrangeSecondaryDark = Color(0xFFE6BEAC)
val OrangeOnSecondaryDark = Color(0xFF432A1E)
val OrangeSecondaryContainerDark = Color(0xFF5C4032)
val OrangeOnSecondaryContainerDark = Color(0xFFFFDBCC)
val OrangeBackgroundDark = Color(0xFF201A17)
val OrangeOnBackgroundDark = Color(0xFFECE0DB)
val OrangeSurfaceDark = Color(0xFF201A17)
val OrangeOnSurfaceDark = Color(0xFFECE0DB)
val OrangeSurfaceVariantDark = Color(0xFF52443C)
val OrangeOnSurfaceVariantDark = Color(0xFFD7C2B8)
val OrangeOutlineDark = Color(0xFF9F8D83)

// Pink Theme
val PinkPrimary = Color(0xFFE91E63)
val PinkOnPrimary = Color(0xFFFFFFFF)
val PinkPrimaryContainer = Color(0xFFFFD9E2)
val PinkOnPrimaryContainer = Color(0xFF3E001D)
val PinkSecondary = Color(0xFF74565F)
val PinkOnSecondary = Color(0xFFFFFFFF)
val PinkSecondaryContainer = Color(0xFFFFD9E2)
val PinkOnSecondaryContainer = Color(0xFF2B151C)
val PinkBackground = Color(0xFFFFFBFF)
val PinkOnBackground = Color(0xFF201A1B)
val PinkSurface = Color(0xFFFFFBFF)
val PinkOnSurface = Color(0xFF201A1B)
val PinkSurfaceVariant = Color(0xFFF2DDE1)
val PinkOnSurfaceVariant = Color(0xFF514346)
val PinkOutline = Color(0xFF837376)

// Pink Dark
val PinkPrimaryDark = Color(0xFFFFB1C4)
val PinkOnPrimaryDark = Color(0xFF650031)
val PinkPrimaryContainerDark = Color(0xFF8E0047)
val PinkOnPrimaryContainerDark = Color(0xFFFFD9E2)
val PinkSecondaryDark = Color(0xFFE3BDC6)
val PinkOnSecondaryDark = Color(0xFF422931)
val PinkSecondaryContainerDark = Color(0xFF5B3F47)
val PinkOnSecondaryContainerDark = Color(0xFFFFD9E2)
val PinkBackgroundDark = Color(0xFF201A1B)
val PinkOnBackgroundDark = Color(0xFFEBE0E1)
val PinkSurfaceDark = Color(0xFF201A1B)
val PinkOnSurfaceDark = Color(0xFFEBE0E1)
val PinkSurfaceVariantDark = Color(0xFF514346)
val PinkOnSurfaceVariantDark = Color(0xFFD5C2C5)
val PinkOutlineDark = Color(0xFF9E8C90)
